config/routes.rb
Rails.application.routes.draw do
  
  root "events#index"
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show] 
  resources :events, only: [:index, :new, :create, :show] do
    resources :attendances, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"

end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true, length: { minimum: 6 }
  validates :location, presence: true, length: {minimum: 3 }

  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances

  scope :past, -> { where("date < ?", Date.today) }
  scope :upcoming, -> { where("date >= ?", Date.today) }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    if @event.attendees.include? current_user
      redirect_to @event
    else
      @event.attendees << current_user
      redirect_to @event
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  def index
    @events = Event.order(:date).all
    # @past_events = Event.where("date < ?", Date.today).order(:date)
    # @upcoming_events = Event.where("date >= ?", Date.today).order(:date)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :date, :time)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<%= render :partial => "/shared/navbar" %>
<section>
  <h1>Upcoming events</h1>
<% if user_signed_in? %>
<div><%= button_to "Create an event", new_event_path, method: :get, :id => "create-button" %></div><br>
<% end %>
<% @events.upcoming.each do |event| %>
  <div>
    <p><strong><%= link_to event.title, event_path(event) %></strong></p><br>
    <p><strong>Location: </strong><%= event.location %></p><br>
    <p><strong>Date: </strong><%= event.date.strftime('%m/%d/%Y') %></p><br>
    <p><strong>Start Time: </strong><%= event.time.strftime('%H:%M') %></p><br>
  </div><br>
<% end %>
</section>
<section>
  <h1>Past events</h1>
<% @events.past.each do |event| %>
  <div>
    <p><strong><%= link_to event.title, event_path(event) %></strong></p><br>
    <p><strong>Location: </strong><%= event.location %></p><br>
    <p><strong>Date: </strong><%= event.date.strftime('%m/%d/%Y') %></p><br>
    <p><strong>Start Time: </strong><%= event.time.strftime('%H:%M') %></p><br>
  </div><br>
<% end %>
</section>

app/views/events/new.html.erb
<%= render :partial => "/shared/navbar" %>
<section>
  <h1>Create an event</h1>

  <%= form_with model: @event do |f| %>

  <h2 class="form-dividing-text">Event Details</h2>

  <div class="input-div">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="input-div">
    <%= f.label :location %><br />
    <%= f.text_field :location, autofocus: true %>
  </div>

  <h2 class="form-dividing-text">Event Start Date & Time</h2>

  <div class="input-div">
    <%= f.label :date %><br />
    <%= f.date_field :date, autofocus: true %>
  </div>

  <div class="input-div">
    <%= f.label :time %><br />
    <%= f.time_field :time, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create Event", :class => "button" %>
  </div>

  <% end %>

</section>

app/views/events/show.html.erb
<%= render :partial => "/shared/navbar" %>
<section>
  <h1><%= @event.title %></h1>
  <h3><%= @event.location %></h3>
  <h2 class="form-dividing-text">Event Details</h2><br>
  <p><strong>Date: </strong><%= @event.date.strftime('%m/%d/%Y') %></p><br>
  <p><strong>Start Time: </strong><%= @event.time.strftime('%H:%M') %></p><br>
  <% user_name = @event.creator.first_name + " " + @event.creator.last_name %>
  <p><strong>Host:</strong> <%= link_to user_name, user_path(@event.creator_id) %></p>
  
  <div class="actions">
    <%= button_to "Attend Event", event_attendances_path(@event), :class => "button" %>
  </div>

</section>
<section>
  <h2 class="form-dividing-text">Attendees</h2><br>
  <% @event.attendees.each do |attendee| %>
  <p><%= attendee.first_name%> <%= attendee.last_name%></p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav id="navbar">
  <p class="logo">eventbright</p>
  <ul>
    <% if user_signed_in? %>
    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <li><%= link_to "Sign In", new_user_session_path %></li>
    <% end %>
    <li><%= link_to "Home", root_path %></li>
  </ul> 
</nav>

app/views/users/show.html.erb
<%= render :partial => "/shared/navbar" %>

  <h1><%= @user.first_name %> <%= @user.last_name %></h1>

    <h2 class="form-dividing-text">Organized Events</h2><br>
    <% @user.created_events.each do |event| %>
    <p><%=link_to event.title, event_path(event.id) %></p>
    <% end %>

    <h2 class="form-dividing-text">Attended Events</h2><br>
    <% @user.attended_events.each do |event| %>
    <p><%=link_to event.title, event_path(event.id) %></p>
    <% end %>